# Generated by Django 3.1.1 on 2020-10-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapi', '0002_auto_20201005_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
