# Generated by Django 3.1.1 on 2020-10-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapi', '0005_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='jandexid',
            field=models.IntegerField(default=0),
        ),
    ]
